# Generated by Django 4.2.7 on 2023-12-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtName', models.CharField(max_length=255)),
                ('courtType', models.CharField(max_length=255)),
                ('locationCity', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
